---
# maintains versions and can overwrite all.yml
canton:
  migration_id: "1"
  participant:
    version: 0.5.1
    jar_ext: "3.4.7"
    # LEDGER_API_ADMIN_USER
    admin_user_id: "YAn59YABoqHGsDV5XVst3ge30YYUb9cs@clients"
    # AUTH_JWKS_URL
    auth_jwks_url: "https://dev-coqploudjmtrcag8.us.auth0.com/.well-known/jwks.json"
    # LEDGER_API_AUTH_AUDIENCE
    target_audience: https://canton.network.global
  app:
    version: 0.5.1
    # SPLICE_APP_VALIDATOR_LEDGER_API_AUTH_URL
    auth_wellknown_url: "https://dev-coqploudjmtrcag8.us.auth0.com/.well-known/openid-configuration"
    # SPLICE_APP_VALIDATOR_LEDGER_API_AUTH_CLIENT_ID
    client_id: "YAn59YABoqHGsDV5XVst3ge30YYUb9cs"
    # SPLICE_APP_VALIDATOR_SV_SPONSOR_ADDRESS
    sponsor_address: "https://sv.sv-1.dev.global.canton.network.sync.global"
    # SPLICE_APP_VALIDATOR_SCAN_ADDRESS
    scan_address: "https://scan.sv-1.dev.global.canton.network.sync.global"
    # SPLICE_APP_VALIDATOR_LEDGER_API_AUTH_USER_NAME
    admin_user_id: "YAn59YABoqHGsDV5XVst3ge30YYUb9cs@clients"
    # SPLICE_APP_VALIDATOR_WALLET_USER_NAME
    wallet_user: "auth0|68edf9735d315e880487926a"
    # SPLICE_APP_VALIDATOR_PARTY_HINT
    party_hint: "Encapsulate-Devnet-1"
    # SPLICE_APP_VALIDATOR_AUTH_AUDIENCE
    auth_audience: https://app.canton.devnet.encapsulate.xyz
    # SPLICE_APP_VALIDATOR_AUTH_JWKS_URL
    auth_jwks_url: "https://dev-coqploudjmtrcag8.us.auth0.com/.well-known/jwks.json"
    # SPLICE_APP_VALIDATOR_PARTICIPANT_IDENTIFIER
    participant_id: "Encapsulate-Devnet-1"
  wallet:
    version: 0.5.1
    auth_url: "https://dev-coqploudjmtrcag8.us.auth0.com"
    client_id: WiKQWSGTL2SUXhJLsX62R9xY5SjC0um8
    network_name: "Canton Network"
    network_url: "https://www.canton.network/hubfs/cn-favicon-05%201-1.png"
    amulet_name: "Canton Coin"
    amulet_acronym: "CC"
    service_name: "Canton Name Service"
    service_acronym: "CNS"
  cns:
    version: 0.5.1
    auth_url: "https://dev-coqploudjmtrcag8.us.auth0.com"
    client_id: gYozCVaFrD57RJr7m58haoWvUd1JTS7O
